version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: app/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./weather.db:/app/weather.db   # persist your sqlite db
    # environment: (add if you have env vars)

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.ui
    ports:
      - "8501:8501"
    depends_on:
      - backend

  # Optional: Ollama (if you want to run the model in Docker)
  # ollama:
  #   image: ollama/ollama:latest
  #   ports:
  #     - "11434:11434"
